# Phải có tên node ở đầu và thụt lề 2 khoảng trắng cho các tham số
slam_toolbox:
  ros__parameters:
    # Khung tọa độ
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # Chế độ tạo TF tự động
    mode: mapping
    pub_map_to_odom: true
    pub_odom_to_base: false

    # Cấu hình xử lý (Sửa lỗi Queue full)
    transform_timeout: 1.0
    scan_buffer_size: 100
    minimum_time_interval: 0.15
    
    # Plugin xử lý
    solver_plugin: solver_plugins::CeresSolver

    map_update_interval: 0.5        # Cập nhật bản đồ mỗi 0.5 giây

    # 2. Ngưỡng di chuyển để vẽ tiếp (Rất quan trọng)
    # Giảm các giá trị này xuống để robot di chuyển nhẹ là map đã vẽ thêm
    minimum_travel_distance: 0.05   # Vẽ thêm sau mỗi 5cm (mặc định thường là 0.1 hoặc 0.2)
    minimum_travel_heading: 0.05    # Vẽ thêm sau mỗi ~3 độ quay

    # 3. Tối ưu hóa việc "Fill" vùng trống
    max_laser_range: 12.0           # Đảm bảo tầm quét bao quát được phòng
    # Tăng độ tin cậy để lấp đầy các ô trống nhanh hơn
    map_start_at_dock: false
    
    # 4. Sửa lỗi "khựng" khi quét liên tục
    # Tăng thời gian chờ TF để tránh việc bỏ lỡ gói tin laser khi CPU bận
    transform_timeout: 1.0
